name: eslint

on:
  workflow_dispatch:
  push:
    branches: [main, reorg]
  pull_request:
    branches: [main, reorg]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run eslint
        run: |
          cd src/muwanx/template
          npx eslint .
